"""baseline

Revision ID: 8dfe900b00ed
Revises: 
Create Date: 2026-03-22 23:29:31.003660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dfe900b00ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_thermal_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_rtj_log'))
        batch_op.drop_index(batch_op.f('idx_rtj_station'))
        batch_op.drop_index(batch_op.f('idx_rtj_status'))

    op.drop_table('receipt_thermal_jobs')
    op.drop_table('inbound_deliveries')
    op.drop_table('receipt_sequences')
    with op.batch_alter_table('delivery_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dr_customer'))
        batch_op.drop_index(batch_op.f('idx_dr_delivered_at'))
        batch_op.drop_index(batch_op.f('idx_dr_delivery'))
        batch_op.drop_index(batch_op.f('receipt_number'))

    op.drop_table('delivery_receipts')
    with op.batch_alter_table('receipt_pdf_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_rpj_log'))
        batch_op.drop_index(batch_op.f('idx_rpj_status'))
        batch_op.drop_index(batch_op.f('provider_message_id'))

    op.drop_table('receipt_pdf_jobs')
    op.drop_table('financial_report_runs')
    op.drop_table('product_suppliers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_created'))
        batch_op.drop_index(batch_op.f('idx_audit_table_record'))
        batch_op.drop_index(batch_op.f('idx_audit_user'))

    op.drop_table('audit_log')
    with op.batch_alter_table('receipt_sms_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('gateway_message_id'))
        batch_op.drop_index(batch_op.f('idx_rsj_dlr'))
        batch_op.drop_index(batch_op.f('idx_rsj_gateway_id'))
        batch_op.drop_index(batch_op.f('idx_rsj_log'))

    op.drop_table('receipt_sms_jobs')
    with op.batch_alter_table('inbound_delivery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_idi_delivery'))
        batch_op.drop_index(batch_op.f('idx_idi_product'))

    op.drop_table('inbound_delivery_items')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('customer_type',
               existing_type=mysql.ENUM('walk_in', 'account', 'wholesale'),
               nullable=True,
               existing_server_default=sa.text("'walk_in'"))
        batch_op.alter_column('credit_limit',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('credit_balance',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('deleted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_customers_type'))
        batch_op.drop_index(batch_op.f('idx_customers_zone'))

    with op.batch_alter_table('dim_date', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('week_of_year',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('month_num',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('quarter',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('is_public_holiday',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('fact_daily_inventory', schema=None) as batch_op:
        batch_op.alter_column('units_received',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('units_sold',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('units_adjusted',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('stockout_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_fdi_unique'))

    with op.batch_alter_table('fact_daily_sales', schema=None) as batch_op:
        batch_op.alter_column('customer_type',
               existing_type=mysql.ENUM('walk_in', 'account', 'wholesale'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('cash', 'mpesa', 'bank_transfer', 'credit', 'cheque'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('units_sold',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('gross_revenue',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('discount_total',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('tax_total',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('net_revenue',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('transaction_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_fds_date'))
        batch_op.drop_index(batch_op.f('idx_fds_product'))
        batch_op.drop_index(batch_op.f('idx_fds_unique'))

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.alter_column('reference_type',
               existing_type=mysql.ENUM('sale_transaction', 'inbound_delivery', 'manual', 'purchase_order'),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_im_created'))
        batch_op.drop_index(batch_op.f('idx_im_product'))
        batch_op.drop_index(batch_op.f('idx_im_ref'))
        batch_op.drop_index(batch_op.f('idx_im_type'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_type',
               existing_type=mysql.ENUM('standard', 'credit_note', 'proforma', 'consolidated'),
               nullable=True,
               existing_server_default=sa.text("'standard'"))
        batch_op.alter_column('invoice_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('tax_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('kra_status',
               existing_type=mysql.ENUM('not_submitted', 'pending', 'submitted', 'accepted', 'rejected'),
               nullable=True,
               existing_server_default=sa.text("'not_submitted'"))
        batch_op.alter_column('kra_submitted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('kra_accepted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_inv_date'))
        batch_op.drop_index(batch_op.f('idx_inv_kra_status'))

    with op.batch_alter_table('outbound_deliveries', schema=None) as batch_op:
        batch_op.alter_column('scheduled_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('delivered_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('scheduled', 'in_transit', 'delivered', 'failed', 'rescheduled'),
               nullable=True,
               existing_server_default=sa.text("'scheduled'"))
        batch_op.alter_column('signature_captured',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_od_customer'))
        batch_op.drop_index(batch_op.f('idx_od_driver'))
        batch_op.drop_index(batch_op.f('idx_od_scheduled'))
        batch_op.drop_index(batch_op.f('idx_od_status'))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('unit_of_measure',
               existing_type=mysql.ENUM('litre', '500ml', '1L', '5L', '10L', '20L', 'carton', 'bottle', 'unit'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('is_refill',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_deposit',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('current_stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('min_stock_level',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('reorder_qty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('deleted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_products_category'))
        batch_op.drop_index(batch_op.f('idx_products_stock'))

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_poi_po'))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'pending_approval', 'approved', 'declined', 'received', 'partial', 'cancelled'),
               nullable=True,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('approved_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_po_status'))
        batch_op.drop_index(batch_op.f('idx_po_supplier'))

    with op.batch_alter_table('receipt_print_log', schema=None) as batch_op:
        batch_op.alter_column('digital_ref',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='In-app URL or display token for digital_only receipts',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('queued', 'sent', 'delivered', 'failed'),
               nullable=True,
               existing_server_default=sa.text("'queued'"))
        batch_op.alter_column('dispatched_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_rpl_del_receipt'))
        batch_op.drop_index(batch_op.f('idx_rpl_dispatched'))
        batch_op.drop_index(batch_op.f('idx_rpl_receipt'))
        batch_op.drop_constraint(batch_op.f('fk_rpl_del_receipt'), type_='foreignkey')
        batch_op.drop_column('delivery_receipt_id')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.alter_column('kra_status',
               existing_type=mysql.ENUM('not_required', 'not_submitted', 'submitted', 'accepted', 'rejected'),
               nullable=True,
               existing_server_default=sa.text("'not_required'"))
        batch_op.alter_column('receipt_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('voided_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_rec_customer'))
        batch_op.drop_index(batch_op.f('idx_rec_date'))
        batch_op.drop_index(batch_op.f('idx_rec_kra_status'))
        batch_op.drop_index(batch_op.f('idx_rec_mpesa'))
        batch_op.drop_index(batch_op.f('idx_rec_transaction'))
        batch_op.drop_index(batch_op.f('idx_rec_type'))
        batch_op.drop_column('notes')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('granted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('containers_returned',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_si_product'))
        batch_op.drop_index(batch_op.f('idx_si_transaction'))

    with op.batch_alter_table('sale_transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('discount_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('tax_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('payment_status',
               existing_type=mysql.ENUM('pending', 'paid', 'partial', 'refunded', 'cancelled'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_st_customer'))
        batch_op.drop_index(batch_op.f('idx_st_date'))
        batch_op.drop_index(batch_op.f('idx_st_payment_status'))
        batch_op.drop_index(batch_op.f('idx_st_staff'))

    with op.batch_alter_table('stock_alerts', schema=None) as batch_op:
        batch_op.alter_column('is_resolved',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('resolved_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_sa_product'))
        batch_op.drop_index(batch_op.f('idx_sa_resolved'))

    with op.batch_alter_table('supplier_contacts', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_sc_supplier'))
        batch_op.drop_constraint(batch_op.f('fk_sc_supplier'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['supplier_id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('payment_terms',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('30'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('deleted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('last_login_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('deleted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_users_active'))
        batch_op.drop_index(batch_op.f('idx_users_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_role'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_active'), ['is_active'], unique=False)
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('last_login_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('payment_terms',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('30'))

    with op.batch_alter_table('supplier_contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sc_supplier'), 'suppliers', ['supplier_id'], ['supplier_id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_sc_supplier'), ['supplier_id'], unique=False)
        batch_op.alter_column('is_primary',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('stock_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sa_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('idx_sa_product'), ['product_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('resolved_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('is_resolved',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('sale_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_st_staff'), ['sales_staff_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_st_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_st_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_st_customer'), ['customer_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('payment_status',
               existing_type=mysql.ENUM('pending', 'paid', 'partial', 'refunded', 'cancelled'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('tax_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('discount_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('transaction_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_si_transaction'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_si_product'), ['product_id'], unique=False)
        batch_op.alter_column('containers_returned',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('discount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('granted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('idx_rec_type'), ['receipt_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_rec_transaction'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_rec_mpesa'), ['mpesa_ref'], unique=False)
        batch_op.create_index(batch_op.f('idx_rec_kra_status'), ['kra_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_rec_date'), ['receipt_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_rec_customer'), ['customer_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('voided_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('receipt_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('kra_status',
               existing_type=mysql.ENUM('not_required', 'not_submitted', 'submitted', 'accepted', 'rejected'),
               nullable=False,
               existing_server_default=sa.text("'not_required'"))

    with op.batch_alter_table('receipt_print_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_receipt_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rpl_del_receipt'), 'delivery_receipts', ['delivery_receipt_id'], ['delivery_receipt_id'])
        batch_op.create_index(batch_op.f('idx_rpl_receipt'), ['receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_rpl_dispatched'), ['dispatched_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_rpl_del_receipt'), ['delivery_receipt_id'], unique=False)
        batch_op.alter_column('dispatched_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('queued', 'sent', 'delivered', 'failed'),
               nullable=False,
               existing_server_default=sa.text("'queued'"))
        batch_op.alter_column('digital_ref',
               existing_type=mysql.VARCHAR(length=200),
               comment='In-app URL or display token for digital_only receipts',
               existing_nullable=True)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_po_supplier'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_po_status'), ['status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('draft', 'pending_approval', 'approved', 'declined', 'received', 'partial', 'cancelled'),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
        batch_op.alter_column('total_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('order_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_poi_po'), ['purchase_order_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_products_stock'), ['current_stock'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_category'), ['category'], unique=False)
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('reorder_qty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('min_stock_level',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('current_stock',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('container_deposit',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('is_refill',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('unit_of_measure',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('litre', '500ml', '1L', '5L', '10L', '20L', 'carton', 'bottle', 'unit'),
               existing_nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('outbound_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_od_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_od_scheduled'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_od_driver'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_od_customer'), ['customer_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('signature_captured',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('scheduled', 'in_transit', 'delivered', 'failed', 'rescheduled'),
               nullable=False,
               existing_server_default=sa.text("'scheduled'"))
        batch_op.alter_column('delivered_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_inv_kra_status'), ['kra_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_inv_date'), ['invoice_date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('kra_accepted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('kra_submitted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('kra_status',
               existing_type=mysql.ENUM('not_submitted', 'pending', 'submitted', 'accepted', 'rejected'),
               nullable=False,
               existing_server_default=sa.text("'not_submitted'"))
        batch_op.alter_column('tax_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('invoice_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('invoice_type',
               existing_type=mysql.ENUM('standard', 'credit_note', 'proforma', 'consolidated'),
               nullable=False,
               existing_server_default=sa.text("'standard'"))

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_im_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_im_ref'), ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_im_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_im_created'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('reference_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('sale_transaction', 'inbound_delivery', 'manual', 'purchase_order'),
               existing_nullable=True)

    with op.batch_alter_table('fact_daily_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fds_unique'), ['date_id', 'product_id', 'customer_type', 'payment_method'], unique=True)
        batch_op.create_index(batch_op.f('idx_fds_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_fds_date'), ['date_id'], unique=False)
        batch_op.alter_column('transaction_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('net_revenue',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('tax_total',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('discount_total',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('gross_revenue',
               existing_type=mysql.DECIMAL(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('units_sold',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('cash', 'mpesa', 'bank_transfer', 'credit', 'cheque'),
               existing_nullable=False)
        batch_op.alter_column('customer_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('walk_in', 'account', 'wholesale'),
               existing_nullable=False)

    with op.batch_alter_table('fact_daily_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_fdi_unique'), ['date_id', 'product_id'], unique=True)
        batch_op.alter_column('stockout_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('units_adjusted',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('units_sold',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('units_received',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('dim_date', schema=None) as batch_op:
        batch_op.alter_column('is_public_holiday',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('quarter',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=False)
        batch_op.alter_column('month_num',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=False)
        batch_op.alter_column('week_of_year',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=False)
        batch_op.alter_column('day_of_week',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_customers_zone'), ['zone'], unique=False)
        batch_op.create_index(batch_op.f('idx_customers_type'), ['customer_type'], unique=False)
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('credit_balance',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('credit_limit',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('customer_type',
               existing_type=mysql.ENUM('walk_in', 'account', 'wholesale'),
               nullable=False,
               existing_server_default=sa.text("'walk_in'"))

    op.create_table('inbound_delivery_items',
    sa.Column('item_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('delivery_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('quantity_expected', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantity_received', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unit_cost', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['inbound_deliveries.delivery_id'], name=op.f('fk_idi_delivery')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_idi_product')),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('inbound_delivery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_idi_product'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_idi_delivery'), ['delivery_id'], unique=False)

    op.create_table('receipt_sms_jobs',
    sa.Column('job_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('print_log_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('gateway', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sender_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('recipient_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('message_body', mysql.TEXT(), nullable=False),
    sa.Column('message_type', mysql.ENUM('sms', 'whatsapp'), server_default=sa.text("'sms'"), nullable=False),
    sa.Column('gateway_message_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('dlr_status', mysql.ENUM('pending', 'sent', 'delivered', 'read', 'failed', 'rejected'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('dlr_received_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('cost_units', mysql.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('queued_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('sent_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['print_log_id'], ['receipt_print_log.log_id'], name=op.f('fk_rsj_log')),
    sa.PrimaryKeyConstraint('job_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('receipt_sms_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rsj_log'), ['print_log_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_rsj_gateway_id'), ['gateway_message_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_rsj_dlr'), ['dlr_status'], unique=False)
        batch_op.create_index(batch_op.f('gateway_message_id'), ['gateway_message_id'], unique=True)

    op.create_table('audit_log',
    sa.Column('log_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('action', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('record_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('old_value', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('new_value', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_audit_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_table_record'), ['table_name', 'record_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_created'), ['created_at'], unique=False)

    op.create_table('product_suppliers',
    sa.Column('product_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('supplier_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unit_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('lead_time_days', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('fk_ps_product')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_ps_supplier')),
    sa.PrimaryKeyConstraint('product_id', 'supplier_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('financial_report_runs',
    sa.Column('run_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('report_type', mysql.ENUM('daily_summary', 'monthly_pnl', 'inventory_valuation', 'kra_submission', 'customer_aging'), nullable=False),
    sa.Column('generated_by', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), nullable=False),
    sa.Column('period_end', sa.DATE(), nullable=False),
    sa.Column('export_format', mysql.ENUM('pdf', 'excel', 'csv'), nullable=True),
    sa.Column('file_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('generated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], name=op.f('fk_frr_user')),
    sa.PrimaryKeyConstraint('run_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('receipt_pdf_jobs',
    sa.Column('job_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('print_log_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('pdf_storage_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('pdf_generated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('pdf_size_bytes', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('email_to', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email_cc', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email_subject', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('email_provider', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('provider_message_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('open_tracked', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('opened_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('status', mysql.ENUM('generating', 'ready', 'sent', 'opened', 'bounced', 'failed'), server_default=sa.text("'generating'"), nullable=False),
    sa.Column('failure_reason', mysql.TEXT(), nullable=True),
    sa.Column('queued_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('sent_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['print_log_id'], ['receipt_print_log.log_id'], name=op.f('fk_rpj_log')),
    sa.PrimaryKeyConstraint('job_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('receipt_pdf_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('provider_message_id'), ['provider_message_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_rpj_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_rpj_log'), ['print_log_id'], unique=False)

    op.create_table('delivery_receipts',
    sa.Column('delivery_receipt_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('receipt_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('delivery_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('transaction_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('received_by_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('received_by_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('signature_data', mysql.TEXT(), nullable=True),
    sa.Column('containers_delivered', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('containers_collected', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('condition_notes', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('signed', 'unsigned', 'disputed'), server_default=sa.text("'unsigned'"), nullable=False),
    sa.Column('delivered_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('fk_dr_customer')),
    sa.ForeignKeyConstraint(['delivery_id'], ['outbound_deliveries.delivery_id'], name=op.f('fk_dr_delivery')),
    sa.ForeignKeyConstraint(['transaction_id'], ['sale_transactions.transaction_id'], name=op.f('fk_dr_transaction')),
    sa.PrimaryKeyConstraint('delivery_receipt_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('delivery_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('idx_dr_delivery'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_dr_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_dr_customer'), ['customer_id'], unique=False)

    op.create_table('receipt_sequences',
    sa.Column('seq_date', sa.DATE(), nullable=False),
    sa.Column('prefix', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('last_seq', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('seq_date', 'prefix'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inbound_deliveries',
    sa.Column('delivery_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('supplier_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('received_by', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('delivery_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('delivery_note_ref', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'partial', 'complete', 'rejected'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['received_by'], ['users.user_id'], name=op.f('fk_ind_receiver')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], name=op.f('fk_ind_supplier')),
    sa.PrimaryKeyConstraint('delivery_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('receipt_thermal_jobs',
    sa.Column('job_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('print_log_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('printer_station_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('printer_model', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paper_width_mm', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('80'), autoincrement=False, nullable=False),
    sa.Column('escpos_payload', mysql.MEDIUMBLOB(), nullable=False),
    sa.Column('char_width', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('42'), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('queued', 'printing', 'done', 'jammed', 'error'), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('error_detail', mysql.TEXT(), nullable=True),
    sa.Column('queued_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('printed_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['print_log_id'], ['receipt_print_log.log_id'], name=op.f('fk_rtj_log')),
    sa.PrimaryKeyConstraint('job_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('receipt_thermal_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_rtj_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_rtj_station'), ['printer_station_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_rtj_log'), ['print_log_id'], unique=False)

    # ### end Alembic commands ###
